

version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper:
    build:
      context: ./scraper
    depends_on:
      - db
    volumes:
      - ./scraper:/app
  
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"