

version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: ./scraper
    depends_on:
      - db
    volumes:
      - ./scraper:/app
